### ISSUE TITLE
Driver response is not reflecting in the Mongoose Model API response

### ISSUE THREAD

**Issue by kathirsvn** [stargate/stargate-mongoose#96]
When I invoke, `findOneAndUpdate` API with `upsert` flag is set to `true` and a new document is inserted, the document is supposed to be returned in the API response. The returned document doesn't have `_id` field in it and I have a created a separate issue with JSON API https://github.com/stargate/jsonapi/issues/417

But, when I was trying a workaround, by copying the `upsertedId` field in the `status` to the `_id` field in the `document`, the final mongoose model API output still doesn't have `_id` field.

Response from JSON API

```http
http: --- response 200 POST http://localhost:8181/v1/testks1/products 
{
  "data": {
    "document": {
      "name": "Product 25",
      "isCertified": false,
      "price": 20,
      "__v": 0
    }
  },
  "status": {
    "matchedCount": 0,
    "modifiedCount": 0,
    "upsertedId": "dbe38035-a3fe-48b6-b2f8-41b94e5c6c59"
  }
}
```

Driver returned output (after copying `upsertedId` into `_id` field as a workaround)

```json
{
  "value" : {
    "name": "Product 25",
    "isCertified": false,
    "price": 20,
    "__v": 0,
    "_id":  "dbe38035-a3fe-48b6-b2f8-41b94e5c6c59"
  },
  "ok" : 1
}
```

Mongoose Mode.findOneAndUpdate API response. We could see the `_id` is not part of the returned document

```json
{ "name": "Product 25", "isCertified": false, "price": 20, "__v": 0 }
```

**Comment by vkarpov15** [comment]
@kathirsvn I took a look and the issue is that Mongoose expects the `_id` to be an ObjectId. Mongoose will store a CastError on the document because `_id` is a uuid, not 24 hex characters. For example, the below script demonstrates the issue, `hydrate()` is the function that Mongoose calls internally to create a Mongoose document from a raw query result.

```javascript
'use strict';

const mongoose = require('mongoose');

const Test = mongoose.model('Test', mongoose.Schema({ name: String }));

const doc = Test.hydrate({ _id: 'dbe38035-a3fe-48b6-b2f8-41b94e5c6c59', name: 'foo' });

console.log(doc);
console.log(doc.validateSync().errors['_id']);
```

Here's a working example:

```javascript
'use strict';

const mongoose = require('mongoose');

// Set `_id` to a string
const Test = mongoose.model('Test', mongoose.Schema({ _id: String, name: String }));

const doc = Test.hydrate({ _id: 'dbe38035-a3fe-48b6-b2f8-41b94e5c6c59', name: 'foo' });

// { _id: 'dbe38035-a3fe-48b6-b2f8-41b94e5c6c59', name: 'foo' }
console.log(doc);

```

**Comment by kathirsvn** [comment]
@vkarpov15 With `upsert` `true`, when JSON API creates a document, it always generates an UUID as `_id`. 

- So should we instruct the server to generate the _id's value based on the _id column type (ObjectId, UUID, String, Number, etc.)

Also, I was able to get the `_id` field's type as shown below in `src/driver/collection.ts`'s `get collection`. Should we pass this to the JSON API to generate `_id` based on this type. Otherwise, we'll get back `null` for any `_id` other than UUID type with the current logic.

```typescript
get collection() {
    const _idType = this.conn.models[this.modelName].schema.paths._id.instance;
    logger.info(`_idType: ${_idType}`);
    return this.conn.db.collection(this.name, _idType);
}
```

- Please advice if this is the proper way to get the type of `_id`. 
- Also, is there some similar logic in the `mongoose` as well to handle different types of `_id`?

**Comment by vkarpov15** [comment]
@kathirsvn that is somewhat problematic with how Mongoose is currently implemented, because Mongoose automatically assumes that `_id` is an ObjectId unless the end user tells us otherwise. We don't necessarily need to tell the server to create the `_id` value based on the schema-defined type, we can rely on the user to handle that. What we should handle is Mongoose's default case, because many users don't specify an `_id` type in their schemas.

The ideal approach would be to support `$setOnInsert` with `_id`. That would allow the stargate-mongoose driver to set `_id` on upserts. Unfortunately `$setOnInsert` with `_id` fails with the following error.

```
Error: Command "updateOne" failed with the following errors: [{"message":"Cannot use operator with '_id' field: $setOnInsert","errorCode":"UNSUPPORTED_UPDATE_FOR_DOC_ID","exceptionClass":"JsonApiException"}]
```

Do you think we can fix that on the JSON API side?

If not, an alternative workaround would be for stargate-mongoose to register a global Mongoose plugin that overrides Mongoose's default `_id` to make schemas have string `_id` by default:

```
'use strict';
  
const mongoose = require('mongoose');

// Make all Mongoose schemas have a string _id by default
mongoose.plugin(schema => {
  if (schema.path('_id').options.auto) {
    // Can also add a default to generate uuid
    schema.add({ _id: String });
  }
});

const Test = mongoose.model('Test', mongoose.Schema({ name: String, subdoc: mongoose.Schema({ name: String }) }));

const doc = Test.hydrate({ _id: 'dbe38035-a3fe-48b6-b2f8-41b94e5c6c59', name: 'foo', subdoc: { _id: 'foobar' } });

// { _id: 'dbe38035-a3fe-48b6-b2f8-41b94e5c6c59', name: 'foo', subdoc: { _id: 'foobar' } }
console.log(doc);
```

**Comment by kathirsvn** [comment]
Hi @vkarpov15 As discussed, lets proceed with option 1 where we rely on the user for `_id` via `$setOnInsert` so that we can support multiple data types for `_id` which is missing in option 2.

I created an issue in the JSON API project to support `_id` in `$setOnInsert` https://github.com/stargate/jsonapi/issues/433

I'll test and close this once JSON API adds the support needed for this.
